#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
TOTAL_STAGES=6

banner "Release v0.1.0 to the public Terraform Registry"

REPO="TekaidoSecurity/terraform-provider-comlaude"
VERSION="v0.1.0"

# ── Stage 1: preflight ────────────────────────────────────────────────────
stage "Preflight"
say "Verifying the tree and CI are release-ready."
if ! git diff --quiet || ! git diff --cached --quiet; then
  warn "Working tree is not clean. Commit or stash before releasing."
  exit 1
fi
step "Latest CI run on main:"
gh run list -R "$REPO" --branch main --limit 1
confirm "Is the latest run green (success)?" || exit 1
say "CHANGELOG.md should be finalized for 0.1.0 (drop '(Unreleased)') and committed."
confirm "Is the CHANGELOG committed and pushed?" || exit 1

# ── Stage 2: GPG signing key ──────────────────────────────────────────────
stage "GPG signing key"
say "A dedicated org signing key: the registry verifies release checksums with it."
ask GPG_EMAIL "Email address for the signing key identity:"
ask_secret GPG_PASSPHRASE "Choose a passphrase for the key:"
IDENTITY="Tekaido Security Terraform Provider Signing <$GPG_EMAIL>"
say "Generating RSA-4096 signing key for: $IDENTITY"
gpg --batch --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" \
  --quick-generate-key "$IDENTITY" rsa4096 sign never
FPR=$(gpg --list-secret-keys --with-colons "$GPG_EMAIL" | awk -F: '/^fpr:/ {print $10; exit}')
note "fingerprint: $FPR"
PRIVATE_KEY=$(gpg --armor --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --export-secret-keys "$FPR")
set_secret GPG_PRIVATE_KEY "$PRIVATE_KEY"
set_secret PASSPHRASE "$GPG_PASSPHRASE"
gpg --armor --export "$FPR" > /tmp/comlaude-provider-signing-public.asc
say "Public key exported to /tmp/comlaude-provider-signing-public.asc (needed in stage 5)."

# ── Stage 3: repo goes public ─────────────────────────────────────────────
stage "Make the repository public"
warn "This publishes the full history of $REPO. Point of no easy return."
if confirm "Make $REPO public now?"; then
  gh repo edit "$REPO" --visibility public --accept-visibility-changes
  say "Repository is public."
else
  warn "Skipped. The registry cannot ingest a private repo; rerun when ready."
  exit 1
fi

# ── Stage 4: tag and release ──────────────────────────────────────────────
stage "Tag $VERSION and let goreleaser build"
step "Tagging the current commit and pushing the tag triggers the signed release build."
if confirm "Create and push tag $VERSION now?"; then
  git tag "$VERSION"
  git push origin "$VERSION"
  say "Tag pushed. Watching the Release workflow (this builds, signs, and uploads)..."
  sleep 10
  gh run watch -R "$REPO" $(gh run list -R "$REPO" --workflow Release --limit 1 --json databaseId --jq '.[0].databaseId') --exit-status
  say "Release workflow succeeded."
else
  exit 1
fi

# ── Stage 5: registry onboarding ──────────────────────────────────────────
stage "Terraform Registry onboarding"
step "Sign in to the registry with the GitHub account that owns TekaidoSecurity."
open_url "https://registry.terraform.io/sign-in"
pause "Signed in?"
step "Add the GPG public key to the TekaidoSecurity namespace:"
step "  User Settings -> Signing Keys -> New GPG key -> namespace TekaidoSecurity,"
step "  paste the contents of /tmp/comlaude-provider-signing-public.asc"
open_url "https://registry.terraform.io/settings/gpg-keys"
pause "Key added?"
step "Publish the provider: choose terraform-provider-comlaude from the repo list."
open_url "https://registry.terraform.io/publish/provider"
pause "Provider published and showing v0.1.0?"

# ── Stage 6: verify from a clean consumer ─────────────────────────────────
stage "Verify installation"
VERIFY_DIR=$(mktemp -d)
cat > "$VERIFY_DIR/main.tf" <<'TF'
terraform {
  required_providers {
    comlaude = {
      source  = "TekaidoSecurity/comlaude"
      version = "0.1.0"
    }
  }
}
TF
say "Running terraform init against the public registry..."
if (cd "$VERIFY_DIR" && terraform init -no-color | tail -5); then
  say "Provider installs from the registry. Release complete."
else
  warn "terraform init failed - the registry may still be ingesting; retry in a few minutes:"
  note "  cd $VERIFY_DIR && terraform init"
fi
# ──────────────────────────────────────────────────────────────────────────

finish
